jwt:
  key-algorithm: RSA
  key-size: 2048
  expire: 1000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: NguyenVanSuong@2001
    url: jdbc:mysql://0.0.0.0:3306/jwt
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true